apiVersion : v1
kind : Pod
metadata : 
  name : tomcat-pod0
  labels :
    app : tomcat 
    tier : dev

spec : 
  containers :
    - name : tomcat-container 
      image : vishymails/tomcatimage:1.0 
